{{- if not .Values.proxy.config.existingSecret -}}
{{- $secretName := ( include "proxy.config.secretName" . ) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    {{- include "mcpServer.labels" . | nindent 4 }}
  name: {{ include "proxy.config.secretName" . }}
data:
  {{- range $key, $value := .Values.proxy.config }}
  {{- if (toString $value) }}
  {{ $key }}: {{ toString $value | b64enc }}
  {{- end }}
  {{- end }}
{{- end -}}