# Default Flows used for Obot.
# We have two flows here, since we separated loading (i.e. parsing files into Markdown-in-JSON format) and ingestion
# Since ingestion only works on the pre-processed JSON files, we need a different flow for the loading process, which does
# not expect JSON files to be structured in the knowledge-specific format.
flows:
  obot:
    default: true
    globals:
      ingestion:
        textsplitter:
          chunkSize: 2048
          chunkOverlap: 256
    ingestion:
      - filetypes: [".json"]
        documentloader:
          name: structured # knowledge-specific JSON format (pre-processed input created by `knowledge load`)
    retrieval:
      retriever:
        name: basic
        options:
          topK: 10

  obotload:
    globals:
      ingestion:
        textsplitter:
          chunkSize: 2048
          chunkOverlap: 256
    ingestion:
      - filetypes: [".pdf"]
        documentloader:
          name: smartpdf
      - filetypes: [ ".pptx", ".doc", ".ppt", ".pages" ]
        converter:
          name: soffice
          targetFormat: pdf
        documentloader:
          name: smartpdf
          options:
            fallbackOptions:
              onImageCount: 1
              onTable: true
              onEmptyContent: true



