name: Package tools

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: depot-ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: obot-platform/obot

      - name: Setup Depot
        uses: depot/setup-action@v1

      - name: Build Docker Image
        uses: depot/build-push-action@v1
        with:
          project: bbqjs4tj1g
          context: .
          platforms: linux/amd64
          build-args: |
            TOOL_REGISTRY_REPOS=github.com/${{ github.event.pull_request.head.repo.full_name }}@${{ github.event.pull_request.head.sha }}
