name: Test

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    branches:
      - main

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Run tests
        run: make test

      - name: Run build
        run: make build

  image-build:
    runs-on: depot-ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        uses: depot/build-push-action@v1
        with:
          project: bbqjs4tj1g
          context: .
          platforms: linux/amd64,linux/arm64
          secrets: |
            GITHUB_TOKEN=${{ secrets.GHCR_TOKEN }}
          build-args: |
            TOOL_REGISTRY_REPOS=github.com/${{ github.event.pull_request.head.repo.full_name }}@${{ github.event.pull_request.head.ref }}
